# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MtgBrowse(object):
    def setupUi(self, MtgBrowse):
        MtgBrowse.setObjectName("MtgBrowse")
        MtgBrowse.resize(1120, 1073)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MtgBrowse.sizePolicy().hasHeightForWidth())
        MtgBrowse.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MtgBrowse)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.saveButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.loadButton_1 = QtWidgets.QPushButton(self.centralWidget)
        self.loadButton_1.setObjectName("loadButton_1")
        self.horizontalLayout_3.addWidget(self.loadButton_1)
        self.loadButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.loadButton_2.setObjectName("loadButton_2")
        self.horizontalLayout_3.addWidget(self.loadButton_2)
        self.loadButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.loadButton_3.setObjectName("loadButton_3")
        self.horizontalLayout_3.addWidget(self.loadButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.check_standard = QtWidgets.QCheckBox(self.centralWidget)
        self.check_standard.setObjectName("check_standard")
        self.horizontalLayout_3.addWidget(self.check_standard)
        self.zoomToggleButton = QtWidgets.QPushButton(self.centralWidget)
        self.zoomToggleButton.setObjectName("zoomToggleButton")
        self.horizontalLayout_3.addWidget(self.zoomToggleButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainWidget = QtWidgets.QWidget(self.centralWidget)
        self.mainWidget.setMinimumSize(QtCore.QSize(1100, 930))
        self.mainWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mainWidget.setObjectName("mainWidget")
        self.gridLayout.addWidget(self.mainWidget, 0, 0, 1, 1)
        self.statusBarLabel = QtWidgets.QLabel(self.centralWidget)
        self.statusBarLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBarLabel.setAutoFillBackground(False)
        self.statusBarLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusBarLabel.setObjectName("statusBarLabel")
        self.gridLayout.addWidget(self.statusBarLabel, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevPage = QtWidgets.QPushButton(self.centralWidget)
        self.prevPage.setEnabled(False)
        self.prevPage.setObjectName("prevPage")
        self.horizontalLayout_5.addWidget(self.prevPage)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.nextPage = QtWidgets.QPushButton(self.centralWidget)
        self.nextPage.setEnabled(False)
        self.nextPage.setObjectName("nextPage")
        self.horizontalLayout_5.addWidget(self.nextPage)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MtgBrowse.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MtgBrowse)
        self.mainToolBar.setObjectName("mainToolBar")
        MtgBrowse.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MtgBrowse)
        QtCore.QMetaObject.connectSlotsByName(MtgBrowse)

    def retranslateUi(self, MtgBrowse):
        _translate = QtCore.QCoreApplication.translate
        MtgBrowse.setWindowTitle(_translate("MtgBrowse", "MTGBrowser"))
        self.saveButton.setText(_translate("MtgBrowse", "Save"))
        self.loadButton_1.setText(_translate("MtgBrowse", "Load 1"))
        self.loadButton_2.setText(_translate("MtgBrowse", "Load 2"))
        self.loadButton_3.setText(_translate("MtgBrowse", "Load 3"))
        self.check_standard.setText(_translate("MtgBrowse", "Standard"))
        self.zoomToggleButton.setText(_translate("MtgBrowse", "Zoom"))
        self.statusBarLabel.setText(_translate("MtgBrowse", "Initialized."))
        self.prevPage.setText(_translate("MtgBrowse", "<"))
        self.nextPage.setText(_translate("MtgBrowse", ">"))

