# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MtgBrowse(object):
    def setupUi(self, MtgBrowse):
        MtgBrowse.setObjectName("MtgBrowse")
        MtgBrowse.resize(884, 866)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MtgBrowse.sizePolicy().hasHeightForWidth())
        MtgBrowse.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MtgBrowse)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.check_standard = QtWidgets.QCheckBox(self.centralWidget)
        self.check_standard.setObjectName("check_standard")
        self.horizontalLayout_3.addWidget(self.check_standard)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.imglabel_2 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_2.sizePolicy().hasHeightForWidth())
        self.imglabel_2.setSizePolicy(sizePolicy)
        self.imglabel_2.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_2.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_2.setText("")
        self.imglabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_2.setObjectName("imglabel_2")
        self.gridLayout.addWidget(self.imglabel_2, 0, 4, 1, 1)
        self.imglabel_3 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_3.sizePolicy().hasHeightForWidth())
        self.imglabel_3.setSizePolicy(sizePolicy)
        self.imglabel_3.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_3.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_3.setText("")
        self.imglabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_3.setObjectName("imglabel_3")
        self.gridLayout.addWidget(self.imglabel_3, 0, 5, 1, 1)
        self.imglabel_10 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_10.sizePolicy().hasHeightForWidth())
        self.imglabel_10.setSizePolicy(sizePolicy)
        self.imglabel_10.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_10.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_10.setText("")
        self.imglabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_10.setObjectName("imglabel_10")
        self.gridLayout.addWidget(self.imglabel_10, 1, 7, 1, 1)
        self.imglabel_1 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_1.sizePolicy().hasHeightForWidth())
        self.imglabel_1.setSizePolicy(sizePolicy)
        self.imglabel_1.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_1.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_1.setText("")
        self.imglabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_1.setObjectName("imglabel_1")
        self.gridLayout.addWidget(self.imglabel_1, 0, 3, 1, 1)
        self.imglabel_4 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_4.sizePolicy().hasHeightForWidth())
        self.imglabel_4.setSizePolicy(sizePolicy)
        self.imglabel_4.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_4.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_4.setText("")
        self.imglabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_4.setObjectName("imglabel_4")
        self.gridLayout.addWidget(self.imglabel_4, 0, 6, 1, 1)
        self.imglabel_5 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_5.sizePolicy().hasHeightForWidth())
        self.imglabel_5.setSizePolicy(sizePolicy)
        self.imglabel_5.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_5.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_5.setText("")
        self.imglabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_5.setObjectName("imglabel_5")
        self.gridLayout.addWidget(self.imglabel_5, 0, 7, 1, 1)
        self.imglabel_6 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_6.sizePolicy().hasHeightForWidth())
        self.imglabel_6.setSizePolicy(sizePolicy)
        self.imglabel_6.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_6.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_6.setText("")
        self.imglabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_6.setObjectName("imglabel_6")
        self.gridLayout.addWidget(self.imglabel_6, 1, 3, 1, 1)
        self.imglabel_7 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_7.sizePolicy().hasHeightForWidth())
        self.imglabel_7.setSizePolicy(sizePolicy)
        self.imglabel_7.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_7.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_7.setText("")
        self.imglabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_7.setObjectName("imglabel_7")
        self.gridLayout.addWidget(self.imglabel_7, 1, 4, 1, 1)
        self.imglabel_14 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_14.sizePolicy().hasHeightForWidth())
        self.imglabel_14.setSizePolicy(sizePolicy)
        self.imglabel_14.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_14.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_14.setText("")
        self.imglabel_14.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_14.setObjectName("imglabel_14")
        self.gridLayout.addWidget(self.imglabel_14, 2, 6, 1, 1)
        self.imglabel_8 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_8.sizePolicy().hasHeightForWidth())
        self.imglabel_8.setSizePolicy(sizePolicy)
        self.imglabel_8.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_8.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_8.setText("")
        self.imglabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_8.setObjectName("imglabel_8")
        self.gridLayout.addWidget(self.imglabel_8, 1, 5, 1, 1)
        self.imglabel_9 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_9.sizePolicy().hasHeightForWidth())
        self.imglabel_9.setSizePolicy(sizePolicy)
        self.imglabel_9.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_9.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_9.setText("")
        self.imglabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_9.setObjectName("imglabel_9")
        self.gridLayout.addWidget(self.imglabel_9, 1, 6, 1, 1)
        self.imglabel_11 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_11.sizePolicy().hasHeightForWidth())
        self.imglabel_11.setSizePolicy(sizePolicy)
        self.imglabel_11.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_11.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_11.setText("")
        self.imglabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_11.setObjectName("imglabel_11")
        self.gridLayout.addWidget(self.imglabel_11, 2, 3, 1, 1)
        self.imglabel_12 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_12.sizePolicy().hasHeightForWidth())
        self.imglabel_12.setSizePolicy(sizePolicy)
        self.imglabel_12.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_12.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_12.setText("")
        self.imglabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_12.setObjectName("imglabel_12")
        self.gridLayout.addWidget(self.imglabel_12, 2, 4, 1, 1)
        self.imglabel_13 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_13.sizePolicy().hasHeightForWidth())
        self.imglabel_13.setSizePolicy(sizePolicy)
        self.imglabel_13.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_13.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_13.setText("")
        self.imglabel_13.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_13.setObjectName("imglabel_13")
        self.gridLayout.addWidget(self.imglabel_13, 2, 5, 1, 1)
        self.imglabel_15 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imglabel_15.sizePolicy().hasHeightForWidth())
        self.imglabel_15.setSizePolicy(sizePolicy)
        self.imglabel_15.setMinimumSize(QtCore.QSize(252, 351))
        self.imglabel_15.setMaximumSize(QtCore.QSize(252, 351))
        self.imglabel_15.setText("")
        self.imglabel_15.setAlignment(QtCore.Qt.AlignCenter)
        self.imglabel_15.setObjectName("imglabel_15")
        self.gridLayout.addWidget(self.imglabel_15, 2, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevPage = QtWidgets.QPushButton(self.centralWidget)
        self.prevPage.setEnabled(False)
        self.prevPage.setObjectName("prevPage")
        self.horizontalLayout_5.addWidget(self.prevPage)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.nextPage = QtWidgets.QPushButton(self.centralWidget)
        self.nextPage.setEnabled(False)
        self.nextPage.setObjectName("nextPage")
        self.horizontalLayout_5.addWidget(self.nextPage)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MtgBrowse.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MtgBrowse)
        self.mainToolBar.setObjectName("mainToolBar")
        MtgBrowse.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MtgBrowse)
        self.statusBar.setObjectName("statusBar")
        MtgBrowse.setStatusBar(self.statusBar)

        self.retranslateUi(MtgBrowse)
        QtCore.QMetaObject.connectSlotsByName(MtgBrowse)

    def retranslateUi(self, MtgBrowse):
        _translate = QtCore.QCoreApplication.translate
        MtgBrowse.setWindowTitle(_translate("MtgBrowse", "MTGBrowser"))
        self.pushButton.setText(_translate("MtgBrowse", "Save"))
        self.pushButton_4.setText(_translate("MtgBrowse", "Load 1"))
        self.pushButton_3.setText(_translate("MtgBrowse", "Load 2"))
        self.pushButton_2.setText(_translate("MtgBrowse", "Load 3"))
        self.check_standard.setText(_translate("MtgBrowse", "Standard"))
        self.prevPage.setText(_translate("MtgBrowse", "<"))
        self.nextPage.setText(_translate("MtgBrowse", ">"))

